name: omni_bot
description: A new Flutter package.
version: 0.0.1
homepage: https://www.omnisaude.co
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  omni_bot_labels:
    path: labels
  flutter:
    sdk: flutter
  omni_general:
    path: ../../packages/omni_general
  omni_core:
    path: ../../plugins/omni_core
  cupertino_icons: ^1.0.5
  flutter_modular: ^5.0.3
  flutter_triple: ^1.2.7+4
  flutter_svg: ^1.0.3
  flutter_html_all: ^3.0.0-alpha.6
  flutter_html_svg: ^3.0.0-alpha.4
  web_socket_channel: ^2.3.0
  carousel_slider: ^4.2.1
  mime: ^1.0.4
  image_cropper: ^3.0.1
  mask_text_input_formatter: ^2.4.0
  flutter_dotenv: ^5.0.2
  cloud_firestore: 4.7.1
  camera: ^0.10.3

dev_dependencies:
  lint: ^1.5.3

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/avatar/attendance/
    - assets/avatar/bot/
