name: omni_general
description: A new Flutter package.
version: 0.0.1
homepage: https://www.omnisaude.co
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  home_labels:
    path: ../../plugins/omni_core/labels/home_labels
  omni_general_labels:
    path: labels
  flutter:
    sdk: flutter
  omni_measurement:
    path: ../../plugins/omni_measurement
  omni_auth:
    path: ../omni_auth
  omni_core:
    path: ../../plugins/omni_core
  dio: ^4.0.6
  share_plus: ^6.3.1
  lottie: ^2.2.0
  shimmer: ^2.0.0
  qr_flutter: ^4.0.0
  file_picker: ^5.2.5
  photo_view: ^0.14.0
  flutter_svg: ^1.0.3
  image_cropper: ^3.0.1
  firebase_core: ^2.4.1
  flutter_triple: ^1.2.7+4
  image_picker: ^0.8.6+1
  flutter_dotenv: ^5.0.2
  flutter_modular: ^5.0.3
  pdfx: ^2.3.0
  internet_file: ^1.2.0
  shared_preferences: ^2.0.17
  firebase_messaging: ^14.2.1
  flutter_screenutil: ^5.6.1
  permission_handler: ^10.2.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  mask_text_input_formatter: ^2.4.0
  flutter_local_notifications: ^13.0.0
  syncfusion_flutter_datepicker: ^23.1.41
  calendar_date_picker2: ^0.3.7
  #flutter_blue: ^0.8.0
  flutter_blue_plus: ^1.12.6
  camera: ^0.10.3
  local_auth: ^2.1.3
  geolocator: ^9.0.2
dev_dependencies:
  lint: ^1.5.3

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/alert/
    - assets/avatar/doctor/
    - assets/avatar/user/
    - assets/bottom_bar/
    - assets/error/
    - assets/icons/
    - assets/lottie/
    - assets/modules/bot/
    - assets/modules/caregiver/
    - assets/modules/categories/
    - assets/modules/drug_control/
    - assets/modules/extra_data/
    - assets/modules/extract_coparticipation/
    - assets/modules/extract_utilization/
    - assets/modules/features_contacts/
    - assets/modules/guide_providers/
    - assets/modules/health_units/
    - assets/modules/income_tax_statement/
    - assets/modules/informative/
    - assets/modules/measurement/
    - assets/modules/mediktor/
    - assets/modules/exit/
    - assets/modules/plan_card/
    - assets/modules/procedure/
    - assets/modules/refund_tab_status/
    - assets/modules/reimbursement/
    - assets/modules/scheduling/
    - assets/modules/scheduling/presential/
    - assets/modules/scheduling/teleattendence/
    - assets/modules/token/
    - assets/modules/vaccine/
    - assets/modules/duplicate_ticket/
    - assets/modules/direct_debit/
    - assets/modules/pharma_discounts/
    - assets/modules/exams_discounts/
    - assets/modules/other_discounts/
    - assets/success/
    - assets/test/
    - assets/biometrics/
