// ignore: constant_identifier_names
const Map<String, String> DRUG_CONTROL_INTERVALS = {
  '1-x-h': 'Cada hora (1h)',
  '2-x-h': 'Cada duas horas (2h)',
  '3-x-h': 'Cada três horas (3h)',
  '4-x-h': 'Cada quatro horas (4h)',
  '5-x-h': 'Cada cinco horas (5h)',
  '6-x-h': 'Cada seis horas (6h)',
  '8-x-h': 'Cada oito horas (8h)',
  '12-x-h': 'Cada 12 horas (12h)',
  '24-x-h': 'Cada 24 horas (24h)',
  '36-x-h': 'Cada 36 horas (36h)',
  '48-x-h': 'Cada 48 horas (48h)',
  '72-x-h': 'Cada 72 horas (72h)',
  '1-/-d': '1x - Uma vez por dia',
  '3-/-d': '3x - Três vezes por dia',
  '4-/-d': '4x - Quatro vezes por dia',
  '5-/-d': '5x - Cinco vezes por dia',
  '6-/-d': '6x - Seis vezes por dia',
  '7-/-d': '7x - Sete vezes por dia',
  '8-/-d': '8x - Oito vezes por dia',
  '9-/-d': '9x - Nove vezes por dia',
  '10-/-d': '10x - Dez vezes por dia',
  '11-/-d': '11x - Onze vezes por dia',
  '12-/-d': '12x - Doze vezes por dia',
  '15-x-d': '15/15 - De quinze em quinze dias',
  '1-/-s': '1x - Uma vez por semana',
  '2-/-s': '2x - Duas vezes por semana',
  '3-/-s': '3x - Três vezes por semana',
  '4-/-s': '4x - Quatro vezes por semana',
  '5-/-s': '5x - Cinco vezes por semana',
  '6-/-s': '6x - Seis vezes por semana',
  '7-/-s': '7x - Sete vezes por semana',
  '1-x-m': '1x - Uma vez por mês',
};
