name: mediconahora
description: A new Flutter application.

publish_to: "none"

version: 2.0.10+29

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  omni_core:
    path: ../../plugins/omni_core
  omni_auth:
    path: ../../packages/omni_auth
  encrypt: ^5.0.1
  google_fonts: ^4.0.2
  flutter_dotenv: ^5.0.2
  webview_flutter: ^3.0.1
  carousel_slider: ^4.2.1
  calendar_date_picker2: ^0.3.7
  anchor_scroll_controller: ^0.4.2
  camera: ^0.10.3
  dashed_rect: ^0.0.4
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  local_auth: ^2.1.3
  internet_file: ^1.2.0
  flutter_slidable: ^2.0.0
  geolocator: ^9.0.2
  secure_application: ^3.8.0
  flutter_webview_plugin: ^0.4.0



# dependency_overrides:
###Sobrescrever labels###
  # omni_core_labels:
  #   path: assets/labels/omni_core_labels
###Sobrescrever labels###

dev_dependencies:
  lint: ^2.0.1

  flutter_launcher_icons: ^0.11.0
  derry: ^1.5.0

scripts:
  build:
    - flutter build appbundle --no-tree-shake-icons
    - flutter build ipa --no-tree-shake-icons
  buildapk:
    - flutter build apk --no-tree-shake-icons
  buildbundle:
    - flutter build appbundle --no-tree-shake-icons
  flutterclean:
    - flutter clean
    - flutter pub get

  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path: "assets/logo/icon_app.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo/
    - assets/presentation/
    - assets/labels/
