include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  errors:
    missing_required_param: error
    missing_return: error
    parameter_assignments: error
  exclude:
    - "lib/gen/**/*.dart"

linter:
  rules:
    overridden_fields: false
    sort_pub_dependencies: false
    sort_constructors_first: false
    prefer_single_quotes: true
    avoid_function_literals_in_foreach_calls: false
    avoid_positional_boolean_parameters: false
    unnecessary_raw_strings: false
    public_member_api_docs: false
    always_specify_types: false
    lines_longer_than_80_chars: true
