name: omni_scheduling
description: A new Flutter package.
version: 0.0.1
homepage: https://www.omnisaude.co
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  omni_scheduling_labels:
    path: labels
  flutter:
    sdk: flutter
  omni_general:
    path: ../../packages/omni_general
  omni_bot:
    path: ../../packages/omni_bot
  omni_video_call:
    path: ../../plugins/omni_video_call
  omni_assistance:
    path: ../../packages/omni_assistance
  omni_core:
    path: ../../plugins/omni_core
  cupertino_icons: ^1.0.5
  flutter_modular: ^5.0.3
  flutter_triple: ^1.2.7+4
  flutter_svg: ^1.0.3
  carousel_slider: ^4.2.1
  dio: ^4.0.6
  shimmer: ^2.0.0
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  cloud_firestore: 4.7.1

dev_dependencies:
  lint: ^1.5.3
  
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/scheduling_details/
    - assets/success/

